#!/usr/bin/env bash
# print message whit sleep 2


# print the msg when receiving the SIGTERM signal
trap "echo I am invincible!!!" SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done;
