#!/usr/bin/env bash
# print "Best School" 10 times using while loop and o the line 9 iteration hi

i=1

while [ "$i" -lt 11 ]; do
  echo "Best Scool"


  # print hi in line 9
  if [ "$i" -eq 9 ]; then
    echo "hi"
  fi


  ((i++))
done
