#!/usr/bin/env bash
# Displays all aciveon the machine IPv4 addresses
# different way to use ifcon, now ip is a new command ifconfig can be missing in some os

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
